movie/inmakes_projects/project_folder/moiveproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
from .views import details

urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.movie_update,name='movie_update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movie/inmakes_projects/project_folder/moiveproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]


if settings.DEBUG:
         urlpatterns += static(settings.STATIC_URL,
                               document_root=settings.STATIC_ROOT)
         urlpatterns += static(settings.MEDIA_URL,
                               document_root=settings.MEDIA_ROOT)

movie/inmakes_projects/project_folder/moiveproject/movieapp/models.py
from django.db import models

# Create your models here.
class updates(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='galleryy')
    def __str__(self):
         return self.name

movie/inmakes_projects/project_folder/moiveproject/movieapp/forms.py
from django import forms
from .models import updates

class MovieForm(forms.ModelForm):
    class  Meta:
        model=updates
        fields=['name','desc','year','img']

movie/inmakes_projects/project_folder/moiveproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import updates
from .forms import MovieForm

# Create your views here.
def index(request):
    movie = updates.objects.all()
    return  render(request,"index.html",{'result':movie})
def details(request,movie_id):
    home= updates.objects.get(id=movie_id)
    return render(request,"details.html",{'page':home})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img=request.FILES['img']
        movie=updates(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,"add.html")

def movie_update(request,id):
     movie=updates.objects.get(id=id)
     form=MovieForm(request.POST or None,request.FILES,instance=movie)
     if form.is_valid():
         form.save()
         return redirect('/')
     return render(request,"edit.html",{'form':form,'movie':movie})

def delete(request,id):
     if request.method=='POST':
        movie=updates.objects.get(id=id)
        movie.delete()
        return  redirect('/')
     return render(request,"delete.html")

movie/inmakes_projects/project_folder/moiveproject/templates/add.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter your movie name"><br><br>
    <input type="text" name="desc" placeholder="enter your description"><br><br>
    <input type="text" name="year" placeholder="enter the year"><br><br>

  Image :  <input type="file" name="img"><br><br>
                      <input type="submit">

</form>
{% endblock %}

movie/inmakes_projects/project_folder/moiveproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{%  static 'style.css'  %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Movie Time
  </a>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

movie/inmakes_projects/project_folder/moiveproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
     Do You Want To Delete this ?
    <input type="submit">
</form>

movie/inmakes_projects/project_folder/moiveproject/templates/details.html
{% extends  'base.html'  %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{page.img.url}}" width="300", height="250">
        </div>

 <div class="col-md-6">
    <h3><b>{{page.name}}</b></h3><br>
    <h4> {{page.desc}}</h4><br>
     <h4>{{page.year}}</h4><br>
<a href="{% url 'movieapp:movie_update' page.id %}">Update</a>
<a href="{% url 'movieapp:delete' page.id %}">Delete</a>
      </div>
          </div>
</div>
{% endblock %}

movie/inmakes_projects/project_folder/moiveproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

movie/inmakes_projects/project_folder/moiveproject/templates/index.html
{% extends  'base.html'  %}
{% block content %}



<div class="container">
    <div class="row">
        {% for i in result %}
        <div class="col-md-3">
            <div class="card" >
  <img src="{{i.img.url}}"  class="Card_img_top" alt="..."  height="250">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text"></p>
    <a href="{% url  'movieapp:details'  i.id %}" class="btn btn-primary">Click Here</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>








{% endblock %}